name: Deploy

on:
  workflow_run:
    workflows: ["pipeline"]
    types:
      - completed
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_deployment: true
          deployment_environment: 'production' # e.g., production, staging
          github_token: ${{ secrets.GITHUB_TOKEN }}