name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  packages: write

jobs:
  tests-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest uvicorn sqlalchemy httpx fastapi jinja2 python-multipart pytest-playwright argon2-cffi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests
      run: |
        pytest -k "unit"

  code-ql:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: python
          build-mode: none

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest uvicorn sqlalchemy httpx fastapi jinja2 python-multipart pytest-playwright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fastapi-app
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fastapi-app
          docker push $IMAGE_NAME --all-tags

  zap-scan:
    runs-on: ubuntu-latest
    needs: build  # This ensures zap-scan runs after the build job completes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Pull FastAPI Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/fastapi-app:latest

      - name: Run FastAPI container
        run: |
          docker run -d -p 8000:8000 --name fastapi-container ghcr.io/${{ github.repository_owner }}/fastapi-app:latest

      - name: Set permissions on the working directory
        run: |
          chmod -R 777 $PWD

      - name: Run ZAP scanner
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run --rm --user root --link fastapi-container:fastapi -v $PWD:/zap/wrk:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8000

      - name: Stop FastAPI container
        run: |
          docker stop fastapi-container
